update login and logout flow
bettersg/verifact_frontend pull request #37
Opened 2021-09-26 04:47 UTC by OoiYueYing

Context: User feedback that they only realize that they need to login/signup on submitting their question. We should inform them before it.

Changes:
1) Bring users who are not logged in to the login page when they click on 'answer the question; button and 3 reaction buttons
2) Add Hi username when user logged in (need graphql help here - not done yet)

![image](https://user-images.githubusercontent.com/40466889/134793945-9ee846db-5d9d-4a44-ab13-b8c3f2528490.png)

2021-09-26 04:50 UTC, OoiYueYing commented on src/components/Navbar.js
> +          {authValue.isLoggedIn ? <NavLink>Hi, <u>User</u></NavLink> : <></>}
Need some guidance on how to create query for auth.User node

2021-09-26 04:51 UTC, OoiYueYing commented on src/components/Navbar.js
> +            ? <NavLink href='/' onClick={handleLogOut}>Log Out</NavLink>
Bring user back to home page after logout

2021-09-26 04:51 UTC, OoiYueYing commented on src/views/Login.js
> +      history.goBack()
Bring user back to where they left off after login

2021-10-03 03:36 UTC, jordantomax requested changes
It's best if you based the PR off main, not off other open PRs. Otherwise, it's best to open only 1 PR as this one is dependent on the other. 

In any case, I'm not exactly clear on what this PR is trying to accomplish. When I click "Ask a Question", I'm not taken to Login as suggested by the description. Though I think that's not a great user experience anyway since it may discourage people from asking questions. I would prefer to have an integrated sign up flow with the ask question, like adding 2 form fields to ask question when user is logged out.

I think it's worth asking a designer about this as well cc @yeesiang-chng

2021-10-03 07:38 UTC, OoiYueYing reviewed
Good catch, my PR missed out the 'Ask a question' button.
This PR is merely a quick fix to bring user to login/Signup page before they can contribute to Verifact.

Agree that we can ask designer to suggest a better user flow.

2021-11-06 14:53 UTC, closed without merging